name: Deployment
concurrency: production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    runs-on: self-hosted
    environment: production
    steps:
      - name: deploy