name: Node.js CI

on:
  push:
    branches: [ "master", "ci-pipeline" ]
  pull_request:
    branches: [ "master", "ci-pipeline" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn ci
    - run: yarn run build --if-present
